create table public.provincias_carga_deseada_segmento (
  prov integer, deseada integer, barrio_popular integer);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (74, 34, 17);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (54, 32, 16);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (82, 34, 17);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (42, 36, 18);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (50, 32, 16);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (62, 34, 17);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (10, 34, 17);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (18, 32, 16);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (14, 34, 17);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (34, 32, 16);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (30, 32, 16);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (86, 32, 16);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (70, 30, 15);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (58, 32, 16);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (26, 32, 16);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (78, 32, 16);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (22, 30, 15);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (02, 36, 18);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (90, 32, 16);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (46, 32, 16);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (38, 32, 16);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (66, 30, 15);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (94, 30, 15);
insert into public.provincias_carga_deseada_segmento (prov, deseada, barrio_popular) values (06, 32, 16);
