INSERT INTO public.provincia VALUES (2, '06', 'Buenos Aires', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (3, '10', 'Catamarca', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (4, '14', 'Córdoba', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (5, '18', 'Corrientes', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (6, '22', 'Chaco', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (7, '26', 'Chubut', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (8, '30', 'Entre Ríos', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (9, '34', 'Formosa', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (10, '38', 'Jujuy', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (11, '42', 'La Pampa', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (12, '46', 'La Rioja', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (13, '50', 'Mendoza', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (14, '54', 'Misiones', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (15, '58', 'Neuquén', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (16, '62', 'Río Negro', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (17, '66', 'Salta', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (18, '70', 'San Juan', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (19, '74', 'San Luis', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (20, '78', 'Santa Cruz', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (21, '82', 'Santa Fe', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (22, '86', 'Santiago del Estero', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (1, '02', 'Ciudad de Buenos Aires', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (23, '90', 'Tucumán', NULL, NULL, NULL, NULL);
INSERT INTO public.provincia VALUES (24, '94', 'Tierra del Fuego', NULL, NULL, NULL, NULL);
