CREATE TABLE public.domicilios
(
    id serial,
    listado_id integer,
    prov integer,
    nom_provincia character varying COLLATE pg_catalog."default",
    ups character varying COLLATE pg_catalog."default",
    nro_area character varying COLLATE pg_catalog."default",
    dpto integer,
    nom_dpto character varying COLLATE pg_catalog."default",
    codaglo integer,
    codloc integer,
    nom_loc character varying COLLATE pg_catalog."default",
    codent character varying COLLATE pg_catalog."default",
    nom_ent character varying COLLATE pg_catalog."default",
    frac integer,
    radio integer,
    mza integer,
    lado integer,
    nro_inicial integer,
    nro_final character varying COLLATE pg_catalog."default",
    orden_recorrido_viv character varying COLLATE pg_catalog."default",
    nro_listado character varying COLLATE pg_catalog."default",
    ccalle integer,
    ncalle character varying COLLATE pg_catalog."default",
    nro_catastral character varying COLLATE pg_catalog."default",
    nrocatastralredef character varying COLLATE pg_catalog."default",
    piso character varying COLLATE pg_catalog."default",
    pisoredef character varying COLLATE pg_catalog."default",
    casa character varying COLLATE pg_catalog."default",
    dpto_habitacion character varying COLLATE pg_catalog."default",
    sector character varying COLLATE pg_catalog."default",
    edificio character varying COLLATE pg_catalog."default",
    entrada character varying COLLATE pg_catalog."default",
    cod_tipo_viv character varying COLLATE pg_catalog."default",
    cod_tipo_vivredef character varying COLLATE pg_catalog."default",
    cod_subt_vivloc character varying COLLATE pg_catalog."default",
    descripcion character varying COLLATE pg_catalog."default",
    descripcion_lado character varying COLLATE pg_catalog."default",
    cod_no_enc character varying COLLATE pg_catalog."default",
    fec_no_enc character varying COLLATE pg_catalog."default",
    motivo_no_enc character varying COLLATE pg_catalog."default",
    fec_alta_viv character varying COLLATE pg_catalog."default",
    fec_ult_mod character varying COLLATE pg_catalog."default",
    cod_postal character varying COLLATE pg_catalog."default",
    orden_recorrido_mza character varying COLLATE pg_catalog."default",
    estado integer,
    esta_supervisado character varying COLLATE pg_catalog."default",
    creadoen character varying COLLATE pg_catalog."default",
    chequeadoen character varying COLLATE pg_catalog."default",
    editadoen character varying COLLATE pg_catalog."default",
    borradoen character varying COLLATE pg_catalog."default",
    creado character varying COLLATE pg_catalog."default",
    chequeado character varying COLLATE pg_catalog."default",
    editado character varying COLLATE pg_catalog."default",
    borrado character varying COLLATE pg_catalog."default",
    actualizador character varying COLLATE pg_catalog."default",
    supervisor character varying COLLATE pg_catalog."default",
    usuario character varying COLLATE pg_catalog."default",
    tipo_base character varying COLLATE pg_catalog."default",
    tipo_tarea character varying COLLATE pg_catalog."default",
    creation_date timestamp without time zone DEFAULT now(),
    last_update timestamp without time zone DEFAULT now(),
    CONSTRAINT domicilios_pkey PRIMARY KEY (id)
)
